### ISSUE TITLE
Is there a chapter on scripting available?

### ISSUE THREAD

**Issue by escapecode** [wjaguar/mtpaint_handbook#1]
Hi all,

I have seen references that mtPaint scripting is documented in appendices or in chapter 10.  I don't see the specified appendices and apparently there isn't a chapter 10 in this repository.  I see that Barry K from PuppyLinux wrote some scripts (refer to http://murga-linux.com/puppy/viewtopic.php?t=94018&start=60&sid=2ebcb5e66908035d6f7cf4fef20c975c) and there is a default script already in mtPaint.  Using that information (and looking a bit over the source code) I get a gist of how scripting functionality works.

If there  is no scripting documentation, I will happily work on some.  If I do, it would be appreciated if people can send me any notes or scripts related that they might have.

**Comment by wjaguar** [comment]
Any help with documenting this part would be **much** appreciated, seeing that presently I'm lacking time for any reasonable work on mtPaint. :(
As for existing sources of info, here they are:
http://www.murga-linux.com/puppy/viewtopic.php?p=791462#791462
http://www.murga-linux.com/puppy/viewtopic.php?p=791872#791872
http://www.murga-linux.com/puppy/viewtopic.php?p=794249#794249
http://www.murga-linux.com/puppy/viewtopic.php?p=794720#794720
http://www.murga-linux.com/puppy/viewtopic.php?p=794891#794891
http://www.murga-linux.com/puppy/viewtopic.php?p=802039#802039
http://www.murga-linux.com/puppy/viewtopic.php?p=845408#845408
http://www.murga-linux.com/puppy/viewtopic.php?p=846108#846108
http://www.murga-linux.com/puppy/viewtopic.php?p=889149#889149
http://www.murga-linux.com/puppy/viewtopic.php?p=889464#889464
http://www.murga-linux.com/puppy/viewtopic.php?p=802333#802333
http://www.murga-linux.com/puppy/viewtopic.php?p=805171#805171

**Comment by wjaguar** [comment]
Chapter 10 added in handbook version 3.49.03
